#!/usr/bin/env python3
from openpyxl import load_workbook

# Load the workbook
wb = load_workbook('/home/user/Vendor-Analysis-Assessment/Vendor Analysis Assessment - Deeba.xlsx')
ws = wb.active

def get_vendor_description(vendor_name):
    """Generate a concise one-line description for each vendor based on their name"""
    vendor_lower = vendor_name.lower()

    # Specific vendor descriptions
    descriptions = {
        'salesforce uk ltd-uk': 'Cloud-based CRM and sales automation platform',
        'navan (tripactions inc)': 'Corporate travel and expense management platform',
        'bdo llp': 'Accounting, audit, and advisory services firm',
        'tog uk properties limited': 'Office space and coworking facilities provider',
        'cloudcrossing bvba': 'Cloud infrastructure and IT services provider',
        'zagrebtower d.o.o.': 'Office building and commercial real estate services',
        'innovent spaces private limited': 'Flexible office space and workspace solutions',
        'weking d.o.o.': 'Office space and commercial property management',
        'jensten insurance brokers': 'Insurance brokerage and risk management services',
        'gpt space & co': 'Coworking and flexible workspace provider',
        'aetna life and casualty ltd': 'Health insurance and employee benefits provider',
        'rsm uk corporate finance llp': 'Corporate finance advisory and consulting services',
        'amazon web services llc': 'Cloud computing infrastructure and platform services',
        'telefonica global services gmbh': 'Telecommunications and IT infrastructure services',
        'hr solution international gmbh': 'Human resources consulting and recruitment services',
        '4i advisory services': 'Business advisory and consulting services',
        'bisley law ltd': 'Legal services and corporate law firm',
        'infosys': 'IT consulting and software development services',
        'big frontier pty ltd (cult of monday)': 'Coworking space and flexible office provider',
        'harmonic group limited': 'Business consulting and advisory services',
        'wework singapore pte. ltd.': 'Coworking spaces and shared office environments',
        'cloud technology solutions ltd': 'Cloud infrastructure and IT solutions provider',
        'navan, inc': 'Corporate travel management and booking platform',
        'tmforum': 'Digital business standards and best practices organization',
        'linkedin ireland limited': 'Professional networking and recruitment platform',
        'kimble applications ltd': 'Professional services automation software',
        'sage uk limited': 'Accounting and financial management software',
        'grant thornton': 'Audit, tax, and advisory services firm',
        'sveuä_x008d_iliå¡te u zagrebu, studentski centar': 'Student accommodation and facilities services',
        'ss&c intralinks inc': 'Secure document sharing and virtual data room platform',
        'veniture d.o.o.': 'Office space and commercial property services',
        'accutrainee limited': 'Training and professional development services',
        'mason frank international ltd': 'Technology recruitment and staffing services',
        'houlihan lokey advisors, llc': 'Investment banking and financial advisory services',
        'vector capital management lp': 'Private equity and investment management firm',
        'hubspot ireland limited': 'Marketing automation and CRM software platform',
        'nefron - obrt za poslovne usluge': 'Business services and consulting provider',
        'planful, inc.': 'Financial planning and budgeting software platform',
        'cognism limited': 'B2B sales intelligence and contact data platform',
        'uberflip': 'Content marketing and experience platform',
        'agram life osiguranje d.o.o.': 'Life insurance and financial protection services',
        'google ireland limited': 'Online advertising, cloud services, and workspace tools',
        'zuric i partneri odvjetnicko drustvo d.o.o.': 'Legal services and law firm',
        'care health insurance company limited': 'Health insurance and medical coverage provider',
        'new star networks(nsn)': 'IT infrastructure and network solutions provider',
        'bupa- supplier': 'Health insurance and healthcare services provider',
        'shree info system solutions pvt ltd': 'IT services and software development company',
        'technet it recruitment': 'IT recruitment and technology staffing services',
        'mightyhive ltd': 'Digital marketing and advertising services',
        'cedar recruitment ltd': 'Recruitment and talent acquisition services',
        'eurofast international ltd-greec': 'Tax and business advisory services',
        'hrvatski telekom d.d.': 'Telecommunications and internet services provider',
        'sodexo svc india private limited': 'Facilities management and food services provider',
        'peakon aps': 'Employee engagement and feedback platform',
        'plus your business ltd': 'Business support and administrative services',
        'benefit systems d.o.o.': 'Employee benefits and wellness program provider',
        'smart group services d.o.o.': 'Business services and facility management',
        'jones lang lasalle (nsw) pty ltd': 'Commercial real estate and property management services',
        'workato, inc.': 'Integration and workflow automation platform',
        'konzum plus d.o.o.': 'Retail and grocery services provider',
        'westbrook advisers': 'Business consulting and advisory services',
        'work easy space solutions private limited': 'Flexible workspace and office solutions provider',
        'taxstudio, ltd.': 'Tax consulting and compliance services',
        'pingo d.o.o.': 'Business services provider',
        'magazin raunalni sistemi d.o.o.': 'Computer systems and IT equipment supplier',
        'tp prime d.o.o.': 'Business services and consulting provider',
        'granttree limited': 'R&D tax credits and innovation funding advisory',
        'cigna sg': 'Health insurance and employee benefits provider',
        'collards chartered accountants': 'Accounting, tax, and business advisory services',
        'bupa australia': 'Health insurance and healthcare services provider',
        '4i management consulting private limited': 'Management consulting and business advisory services',
        'grad zagreb, gradski ured za prostorno ureä\'enje,..': 'Municipal planning and administrative services',
        'bijeli pijesak obrt za poslovno savjetovanje': 'Business consulting and advisory services',
        'ramiro d.o.o.': 'Business services provider',
        'visalogic limited': 'Immigration and visa consulting services',
        'poles ltd - hanbury manor': 'Hotel and event venue services',
        'shoff darby companies': 'Business consulting and advisory services',
        'emerge development consultancy ltd': 'Business development and consulting services',
        'performancepro': 'Performance management and HR software',
        'microsoft ireland operations limited': 'Enterprise software and cloud computing services',
        'catering muring': 'Catering and food services provider',
        'omonia d.o.o.': 'Business services provider',
        'outreach corporation': 'Sales engagement and automation platform',
        'cbre limited': 'Commercial real estate services and property management',
        'studentski centar - split': 'Student accommodation and facilities services',
        'the guardian': 'News media and publishing services',
        'intertrust singapore corporate services pte ltd - csc': 'Corporate services and company administration',
        'goto technologies uk limited': 'Remote access and collaboration software',
        'hrsolution international ag': 'Human resources consulting and services',
        'trello': 'Project management and collaboration software',
        'obrt sjaj sunca': 'Business services provider',
        'telefã³nica compras electrã³nicas s.l.': 'Telecommunications and procurement services',
        'allianz australia workers\' compensation (victoria) limited': 'Workers compensation insurance provider',
        'icici lombard gic ltd': 'General insurance and risk management services',
        'mosaic concept d.o.o.': 'Business consulting and creative services',
        'limes plus d.o.o.': 'Business services provider',
        'mercer limited': 'HR consulting and employee benefits advisory',
        'acclime corporate services': 'Corporate administration and compliance services',
        'green commute initiative': 'Sustainable commuting and bike leasing services',
        'tattu manchester limited': 'Restaurant and dining services',
        'athlete service ltd': 'Sports and fitness services provider',
        'amazon web services inc.': 'Cloud computing infrastructure and platform services',
        'telemach hrvatska d.o.o.': 'Telecommunications and internet services provider',
        'acclime usa, inc': 'Corporate services and business administration',
        'centar za sigurnost d.o.o.': 'Security services and safety consulting',
        'profi bar d.o.o.': 'Bar and hospitality services',
        'pricewaterhousecoopers llp': 'Audit, tax, and consulting services firm',
        'pinnacle partnership ca': 'Business partnership and consulting services',
        'the virtual legal counsel ltd': 'Legal advisory and virtual counsel services',
        'australian payroll professionals pty ltd': 'Payroll processing and administration services',
        'inter continental chennai mahabalipuram resort': 'Hotel and resort accommodation services',
        'jetbrains s.r.o.': 'Software development tools and IDE platforms',
        'crowe horwath revizija d.o.o.': 'Audit and financial advisory services',
        'puducherry backwater resort private limited': 'Hotel and resort accommodation services',
        'orionw llc': 'Business consulting and services provider',
        'adobe systems software': 'Creative software and digital marketing tools',
        'common desk, llc': 'Coworking space and flexible office provider',
        'hep elektra d.o.o.': 'Electricity distribution and energy services',
        'zivi napitak d.o.o.': 'Beverage distribution and retail services',
        'gym4you d.o.o.': 'Fitness center and gym membership services',
        'aha! labs inc': 'Product roadmap and strategy software platform',
        'apple retail uk ltd': 'Technology retail and consumer electronics',
        'kryterion, inc.': 'Online testing and certification platform',
        'npm inc': 'Software package management and developer tools',
        'pinsent masons mpillay llp': 'International law firm and legal services',
        'calm achiever(a unit of mohsin ali vakil)': 'Wellness and consulting services',
        'pluxee india private limited': 'Employee benefits and meal voucher services',
        'oâ€™donnell salzano lawyers': 'Legal services and law firm',
        'papertrail inc': 'Log management and monitoring software platform',
        'sniper systems and solutions private limited': 'IT solutions and systems integration services',
        'trocadero (london) hotel ltd': 'Hotel accommodation and hospitality services',
        'semrush inc': 'SEO and digital marketing analytics platform',
        'golubica parking d.o.o.': 'Parking facility management services',
        'vodafone (australian)': 'Telecommunications and mobile services provider',
        'ikea hrvatska d.o.o.': 'Furniture and home goods retail',
        'orcola d.o.o.': 'Business services provider',
        'info edge india limited': 'Online classifieds and recruitment services',
        'grad split': 'Municipal services and local government',
        't-mobile': 'Mobile telecommunications services provider',
        'akton d.o.o.': 'Business services provider',
        'bureau veritas croatia d.o.o.': 'Testing, inspection, and certification services',
        'cici prudential life insurance co. ltd.': 'Life insurance and financial protection services',
        'ncc services limited': 'IT and business services provider',
        'smartsheet inc.': 'Work management and collaboration platform',
        'good game global d.o.o.': 'Gaming and entertainment services',
        'garaå¾a firule d.o.o.': 'Parking and garage management services',
        'crossland': 'Real estate and property services',
        'it london': 'IT recruitment and staffing services',
        'terrapinn holdings ltd': 'Business events and conference organizer',
        'elemental life solutions llp': 'Business solutions and consulting services',
        'united flow ltd (the goodness project)': 'Catering and food services provider',
        'mcburneys charted accountants': 'Accounting and tax advisory services',
        'cleverland winery resort': 'Winery, resort, and hospitality services',
        'ag grid ltd': 'Data grid and visualization software components',
        'lusha': 'B2B contact and company data platform',
        'my foodiverse llp': 'Catering and food services provider',
        '4imprint direct ltd': 'Promotional products and branded merchandise',
        'city pantry ltd': 'Corporate catering and food delivery services',
        'stipe piric': 'Individual contractor or consultant services',
        'office move london': 'Office relocation and moving services',
        'pink ribbon shop': 'Charitable retail and gift services',
        'starhub ltd (supplier)': 'Telecommunications and broadband services provider',
        'n s shastri and co': 'Accounting and tax consulting services',
        'john smith': 'Individual contractor or consultant services',
        'fabiola thistlewhaite': 'Individual contractor or consultant services',
        'hp inc uk limited': 'Computer hardware and technology equipment',
        'cision pr newswire': 'Press release distribution and media monitoring',
        'george anchor': 'Individual contractor or consultant services',
        'yoxel, inc': 'Cloud communication and collaboration platform',
        'grt hotels and resorts p ltd': 'Hotel and resort accommodation services',
        'apple pty ltd': 'Technology products and consumer electronics',
        'slack technologies limited': 'Team collaboration and messaging platform',
        'g s notary public limited': 'Notary and document authentication services',
        'apple distribution international ltd': 'Technology product distribution and sales',
        'porezno savjetniå¡tvo tuk d.o.o.': 'Tax consulting and advisory services',
        'susan lee': 'Individual contractor or consultant services',
        'ansar madovic': 'Individual contractor or consultant services',
        'radius group, inc': 'Technology consulting and software development',
        'aquila remete d.o.o.': 'Real estate and property services',
        'clime india private limited': 'Business services and consulting provider',
        'golden mean, inc': 'Business consulting and advisory services',
        'paint & fun vl. martina milkova nikolova': 'Entertainment and team building activities',
        'carrington communications': 'Marketing and communications services',
        'crayond digital private limited': 'Digital marketing and technology services',
        'studentski centar karlovac': 'Student accommodation and facilities services',
        'lajnap comedy booking d.o.o.': 'Entertainment booking and event services',
        'british telecommunications': 'Telecommunications and internet services provider',
        'etm concessions ltd': 'Retail concessions and vending services',
        'radisson grt - unit of hotels & resorts pvt ltd': 'Hotel accommodation and hospitality services',
        'ariba inc': 'Procurement and supply chain management software',
        'chamiers recreation club': 'Recreation and social club facilities',
        'quadrant law llc': 'Legal services and law firm',
        'docusign': 'Electronic signature and document management platform',
        'inside edge novated leasing': 'Vehicle leasing and fleet management services',
        'rhea d.o.o.': 'Business services provider',
        'p s recreation club': 'Recreation and social club facilities',
        'fastspring': 'E-commerce and subscription billing platform',
        'dsv solutions a/s': 'Logistics and supply chain management services',
        'curzon green solicitors': 'Legal services and law firm',
        'icare nsw': 'Workers compensation insurance provider',
        'thomas mansfield solicitors limited': 'Legal services and law firm',
        'amazon.co.uk': 'E-commerce and online retail platform',
        'backoffice associates': 'Business process outsourcing and support services',
        'oladi d.o.o.': 'Business services provider',
        'integrated personnel services': 'Recruitment and staffing services',
        'mãœller trgovina zagreb d.o.o.': 'Retail and trading services',
        'lunch nutrition d.o.o.': 'Catering and meal services provider',
        'winmaxi tours & travels': 'Travel agency and tour services',
        'digitalna produkcija j.d.o.o.': 'Digital production and media services',
        'computershare-caboodle technology limited': 'Employee share plan administration software',
        'allianz wa': 'Insurance and financial services provider',
        'trending technology services gmbh': 'IT consulting and technology services',
        'godaddy.com, llc': 'Domain registration and web hosting services',
        'time out group': 'Media, events, and entertainment services',
        'raiffeisenbank austria d.d.': 'Banking and financial services',
        'galop-prijevoz d.o.o.': 'Transportation and logistics services',
        'lane ip limited': 'Intellectual property consulting services',
        'urbani eventi d.o.o.': 'Event planning and management services',
        'smashing media ag': 'Digital media and publishing services',
        'epignosis llc': 'Learning management and training software',
        'croatia airlines': 'Airline and air travel services',
        'bb football scouting j.d.o.o.': 'Sports scouting and recruitment services',
        'boe croatia d.o.o.': 'Business services provider',
        'potomac d.o.o.': 'Business services provider',
        'president hotel and tower co., ltd': 'Hotel accommodation and hospitality services',
        'friends sports club': 'Recreation and sports club facilities',
        'the cycle gap adyar': 'Bicycle retail and services',
        'apple - amer': 'Technology products and consumer electronics',
        'klg - kalra legal group': 'Legal services and immigration law firm',
        'kilgannon & partners llp': 'Business consulting and advisory services',
        'uk postbox limited': 'Virtual mailbox and mail forwarding services',
        'catering iviä‡ d.o.o.': 'Catering and food services provider',
        'blink events': 'Event planning and management services',
        'grafo-jan': 'Printing and graphic services',
        'mesa verde': 'Restaurant and dining services',
        'pixsy inc': 'Image copyright protection and licensing services',
        'dun & bradstreet d.o.o.': 'Business data and analytics services',
        'induslaw': 'Legal services and corporate law firm',
        'trans-agram obrt za dostavu': 'Delivery and courier services',
        'landu law solicitors': 'Legal services and law firm',
        'arena center zagreb d.o.o.': 'Shopping center and retail facilities',
        'obrt za ugostiteljstvo mirakul': 'Hospitality and catering services',
        'oakberry jr d.o.o.': 'Food and beverage retail services',
        'tau on-line d.o.o.': 'Online services and digital solutions',
        'magic mountain saloon': 'Restaurant and bar services',
        'hotel zonar': 'Hotel accommodation and hospitality services',
        'roto dinamic d.o.o.': 'Business services provider',
        'tm forum': 'Industry standards and collaboration organization',
        'marvie hotel - krupa d.o.o.': 'Hotel accommodation and hospitality services',
        'merchandise ltd': 'Promotional products and branded merchandise',
        'yellow submarine d.o.o.': 'Business services provider',
        'streamlinereforms inc': 'Business process improvement consulting',
        'make and grow ltd': 'Business consulting and growth services',
        'obiteljski hoteli d.o.o.': 'Hotel accommodation and hospitality services',
        'rudan d.o.o.': 'Business services provider',
        'entrio tehnologije d.o.o.': 'Event ticketing and technology platform',
        'vivat fina vina d.o.o.': 'Wine retail and distribution services',
        'figma, inc.': 'Collaborative design and prototyping platform',
        'e-disti d.o.o.': 'Business services provider',
        'greencell express private limited': 'Transportation and shuttle services',
        'edwardian pastoria hotels ltd (the londoner)': 'Hotel accommodation and hospitality services',
        'tiganda j.d.o.o.': 'Business services provider',
        'franklin, gringer & cohen, p.c.': 'Legal services and law firm',
        'blitz - cinestar d.o.o.': 'Cinema and entertainment services',
        'lancefield bus service': 'Bus transportation and charter services',
        'super odreä\u017eiå¡te d.o.o.': 'Business services provider',
        'pmi global operations center': 'Project management and business operations',
        'student packers & movers': 'Moving and relocation services',
        'del posto d.o.o.': 'Restaurant and dining services',
        'inicijativa centar za edukaciju': 'Education and training services',
        'niva transport j.d.o.o.': 'Transportation and logistics services',
        'doctor anywhere operations pte ltd': 'Telemedicine and healthcare services',
        'spar hrvatska d.o.o.': 'Retail and grocery services',
        'pepe\'s italian and liquor': 'Restaurant and bar services',
        'pluralsight, llc': 'Online technology training and learning platform',
        'maniax melbourne cbd': 'Entertainment and recreation services',
        'dnsimple': 'Domain management and DNS hosting services',
        'treci posao d.o.o.': 'Business services provider',
        'gaucho restaurants': 'Restaurant and dining services',
        'formswift': 'Online document creation and legal forms platform',
        'safestore ltd': 'Self-storage and storage facility services',
        'split tech city': 'Technology hub and startup community',
        'national securities depository limited(nsdl)': 'Securities depository and financial services',
        'adamma info services private limited': 'IT services and information technology',
        'the riding house cafe': 'Restaurant and cafe services',
        'stillmark zagreb d.o.o.': 'Business services provider',
        'lastpass ireland limited': 'Password management and security software',
        'taste of health': 'Health food and catering services',
        'infodata': 'Data management and IT services',
        'amazon (aus)': 'E-commerce and online retail platform',
        'regency hampers ltd': 'Gift hampers and corporate gifts',
        'bella operation a/s': 'Business services provider',
        'the plant man': 'Plant and landscaping services',
        'media promo plus d.o.o.': 'Marketing and promotional services',
        'expert-ing d.o.o.': 'Engineering and technical consulting',
        'atlassian pty ltd': 'Collaboration and software development tools',
        'djs for u': 'Entertainment and DJ services',
        'freepik company': 'Stock photos and graphic resources platform',
        'nastavni zavod za javno zdravstvo dr. andrija å¡tampar': 'Public health and medical services',
        'rishi events and entainment': 'Event planning and entertainment services',
        'kosmaz technologies croatia': 'IT services and technology solutions',
        'dhl': 'Logistics and international shipping services',
        'hotel laguna d.d.': 'Hotel accommodation and hospitality services',
        'bigshare services private limited': 'Share registry and investor services',
        'zettanet': 'IT infrastructure and network services',
        'hahn air': 'Airline ticketing and distribution services',
        'vitality works': 'Wellness and employee health programs',
        'avoxi inc': 'Cloud communication and phone services',
        'zapier inc.': 'Workflow automation and app integration platform',
        'solarwinds, inc': 'IT management and monitoring software',
        'xenon savjetovanje d.o.o.': 'Business consulting and advisory services',
        'floom ltd': 'Flower delivery and retail platform',
        'notino s.r.o.': 'Beauty products and cosmetics retail',
        'paint&wine, vl. stevo dosen': 'Entertainment and creative workshop services',
        'parcelforce worldwide': 'Parcel delivery and courier services',
        'advena': 'Business services provider',
        'hrvatski nezavisnici izvoznici softvera': 'Software export and technology services',
        'monile j.d.o.o.': 'Business services provider',
        'puzzle promotion j.d.o.o.': 'Marketing and promotional services',
        'zagrebaä_x008d_ki holding d.o.o.': 'Holding company and business services',
        'event ors': 'Event planning and management services',
        'sportkart d.o.o.': 'Sports equipment and retail services',
        'interaction design foundation, inc': 'Online design education and training',
        '(blank)': 'Unknown or unspecified vendor',
        'escape art d.o.o.': 'Entertainment and escape room services',
        'fero-term': 'Business services provider',
        'ustanova za zdravstvenu skrb p.p.': 'Healthcare and medical services',
        'vistaprint': 'Online printing and marketing materials',
        'teb poslovno savjetovanje d.o.o.': 'Business consulting and advisory services',
        'illunis d.o.o.': 'Business services provider',
        'the cook kitchen': 'Catering and food services provider',
        'australian taxation office (ato)': 'Tax collection and government revenue agency',
        'capitol services': 'Business services provider',
        'bonus opinio d.o.o.': 'Business services provider',
        'dhl express (uk) ltd': 'Express delivery and logistics services',
        'kat\'s kitchen d.o.o.': 'Catering and food services provider',
        'soho kitchen ltd': 'Catering and food services provider',
        'fortis trade j.d.o.o.': 'Trading and business services',
        'till trade d.o.o.': 'Trading and business services',
        'pret a manger': 'Restaurant and food retail chain',
        'axil coffee roasters': 'Coffee roasting and cafe services',
        'pepco croatia d.o.o.': 'Retail and discount store chain',
        'lemia d.o.o.': 'Business services provider',
        'retriever llc': 'Business services provider',
        'meluba limited': 'Business services provider',
        'london waste management': 'Waste disposal and recycling services',
        'hilton garden inn - zagreb city hotels d.o.o.': 'Hotel accommodation and hospitality services',
        'lider media d.o.o.': 'Media and publishing services',
        'uptime robot service provider ltd': 'Website monitoring and uptime tracking services',
        'mithras consultants': 'Business consulting and advisory services',
        '6sense insights inc': 'B2B marketing and sales intelligence platform',
        'ico': 'Data protection and information governance services',
        'sportska udruga split': 'Sports club and recreation services',
        'prezzee': 'Digital gift card and voucher platform',
        'inet telecoms ltd.': 'Telecommunications and internet services',
        'wolt enterprises oy': 'Food delivery and courier platform',
        'platinum office d.o.o.': 'Office space and business center services',
        'snappy snaps': 'Photo printing and services',
        'new block d.o.o.': 'Business services provider',
        'cayman islands government': 'Government services and administration',
        'officeworks': 'Office supplies and business services retail',
        'click send pty ltd': 'SMS and communication platform services',
        'kall kwik centre 565': 'Printing and copy services',
        'shilton hospitality llp': 'Hospitality and catering services',
        'axosoft gitkraken': 'Software development and version control tools',
        'istra wine': 'Wine retail and distribution services',
        'gophr': 'Same-day delivery and courier services',
        'pan-pek d.o.o.': 'Bakery and food production services',
        'uber *eats': 'Food delivery platform services',
        'fedex express uk transportation ltd': 'Express delivery and logistics services',
        'garden city d.o.o.': 'Business services provider',
        'livingstone': 'Business services provider',
        'ekupi d.o.o.': 'E-commerce and online retail platform',
        'farmacia - specijalizirana prodavaonica d.o.o.': 'Pharmacy and healthcare retail',
        'cupcake central (life is sweet bakery)': 'Bakery and dessert services',
        'post office ltd': 'Postal and parcel delivery services',
        'currys pc world': 'Electronics and technology retail',
        'brodomerkur d.d.': 'Business services provider',
        'sport vision d.o.o.': 'Sports equipment and apparel retail',
        'harissa d.o.o.': 'Restaurant and food services',
        'specijalisticka ordinacija medicine rada i sporta ina kardos': 'Occupational health and medical services',
        'specijalisticka ordinacija medicine rada helena blazic': 'Occupational health and medical services',
        'ustanova za medicinu rada i sporta dr. novacki': 'Occupational health and sports medicine services',
        'm&s simply food': 'Food retail and grocery services',
        'bakemono bakers melbourne': 'Bakery and food services',
        'coles': 'Supermarket and grocery retail chain',
    }

    return descriptions.get(vendor_lower, 'Business services provider')

# Print table
print("| Vendor Name | Description |")
print("|-------------|-------------|")

for row in ws.iter_rows(min_row=2, values_only=True):
    if row[0]:
        vendor_name = row[0]
        description = get_vendor_description(vendor_name)
        print(f"| {vendor_name} | {description} |")
